targets:
  multidisplay:
    sources:
      include:
        - lib/**       
        - pubspec.*
        - $package$
      exclude:
        - lib/**/generated/**
        - packages/**
    dependencies:
      - tracking_repository:tracking_repository
      - calendar_repository:calendar_repository
      - weather_repository:weather_repository
      - open_meteo_api:open_meteo_api
    builders:
      source_gen:combining_builder:
        enabled: true
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
          build_extensions:
            'lib/{{path}}/{{file}}.dart': 'lib/{{path}}/generated/{{file}}.g.dart'
      json_serializable:
        options:
          field_rename: snake
          checked: true
          explicit_to_json: true
      freezed:
        enabled: true
        options:
          copy_with: true
          build_extensions:
            'lib/{{path}}/{{file}}.dart': 'lib/{{path}}/generated/{{file}}.freezed.dart'
  open_meteo_api:
    sources:
      include:
        - packages/open_meteo_api/lib/src/models/**
      exclude:
        - packages/**/*.g.dart
        - packages/**/*.freezed.dart
        - packages/**/*.firestore_converter.dart
    dependencies:
      - multidisplay:open_meteo_api
    builders:
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
      json_serializable:
        options:
          field_rename: snake
          checked: true
          explicit_to_json: true
  weather_repository:
    sources:
      include:
        - packages/weather_repository/lib/src/models/**
      exclude:
        - packages/**/*.g.dart
        - packages/**/*.freezed.dart
        - packages/**/*.firestore_converter.dart
    dependencies:
      - open_meteo_api
    builders:
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
      json_serializable:
        options:
          field_rename: snake
          checked: true
          explicit_to_json: true
  calendar_repository:
    sources:
      include:
      - packages/calendar_repository/lib/src/models/**
      exclude:
        - packages/**/*.g.dart
        - packages/**/*.freezed.dart
        - packages/**/*.firestore_converter.dart
    builders:
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
      json_serializable:
        options:
          field_rename: snake
          checked: true
          explicit_to_json: true
  tracking_repository:
    sources:
      include:
        - packages/tracking_repository/lib/src/models/**
      exclude:
        - packages/**/*.g.dart
        - packages/**/*.freezed.dart
        - packages/**/*.firestore_converter.dart
    builders:
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
          build_extensions: {'lib/src/models/{{}}.dart': ['lib/src/models/generated/{{}}.g.dart']}
      firestore_converter_generator:
        enabled: true
        options: 
          build_extensions: {'lib/src/models/{{}}.dart': ['lib/src/models/generated/{{}}.firestore_converter.dart']}
      freezed:freezed:
        enabled: true
        options: 
          build_extensions: {'lib/src/models/{{}}.dart': ['lib/src/models/generated/{{}}.freezed.dart']}
      json_serializable:
        options:
          field_rename: snake
          checked: true
          explicit_to_json: true

global_options:
  freezed:freezed:
    runs_before:
      - build_resolvers:transitive_digests