targets:
  multidisplay:
    sources:
      - lib/**       
      - pubspec.*
      - $package$
    dependencies:
      - multidisplay:tracking_repo
      - multidisplay:calendar_repo
      - multidisplay:weather_repo
      - multidisplay:open_meteo
    builders:
      source_gen:combining_builder:
        options:
          enabled: true
          ignore_for_file:
            - implicit_dynamic_parameter
          build_extensions:
            'lib/{{path}}/{{file}}.dart': 'lib/{{path}}/generated/{{file}}.g.dart'
      json_serializable:
        options:
          field_rename: snake
          checked: true
          explicit_to_json: true
      freezed:
        options:
          enabled: true
          copy_with: true
          build_extensions:
            'lib/{{path}}/{{file}}.dart': 'lib/{{path}}/generated/{{file}}.freezed.dart'
  open_meteo:
    sources:
      - packages/open_meteo_api/lib/src/models/**
    builders:
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
      json_serializable:
        options:
          field_rename: snake
          checked: true
          explicit_to_json: true
  weather_repo:
    sources:
      - packages/weather_repository/lib/src/models/**
    dependencies:
      - open_meteo
    builders:
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
      json_serializable:
        options:
          field_rename: snake
          checked: true
          explicit_to_json: true
  calendar_repo:
    sources:
      - packages/calendar_repository/lib/src/models/**
    builders:
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
      json_serializable:
        options:
          field_rename: snake
          checked: true
          explicit_to_json: true
  tracking_repo:
    sources:
      include:
        - packages/tracking_repository/lib/src/models/**
    builders:
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
          build_extensions: {'lib/src/models/{{}}.dart': ['lib/src/models/generated/{{}}.g.dart']}
      firestore_converter_generator:
        enabled: true
        options: 
          build_extensions: {'lib/src/models/{{}}.dart': ['lib/src/models/generated/{{}}.firestore_converter.dart']}
      freezed:freezed:
        enabled: true
        options: 
          build_extensions: {'lib/src/models/{{}}.dart': ['lib/src/models/generated/{{}}.freezed.dart']}
      json_serializable:
        options:
          field_rename: snake
          checked: true
          explicit_to_json: true
