name: multidisplay
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  adaptive_dialog: ^2.1.0
  adaptive_theme: ^3.6.0
  auth_repository:
    path: packages/auth_repository
  bloc: ^8.1.3
  calendar_repository:
    path: packages/calendar_repository
  cloud_firestore: ^4.17.0
  confetti: ^0.7.0
  custom_components:
    path: packages/custom_components
  equatable: ^2.0.5
  expandable_widgets: ^1.0.3+1
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  firebase_remote_config: ^4.4.5
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_calendar_heatmap:
    git:
      url: https://github.com/ericpark/flutter_calendar_heatmap
      ref: main # branch name
  flutter_expandable_fab: ^2.0.0
  flutter_form_bloc: ^0.31.0
  flutter_login: ^5.0.0
  font_awesome_flutter: ^10.7.0
  form_bloc: ^0.31.0
  freezed_annotation: ^2.4.1
  geolocator: ^11.0.0
  google_fonts: ^6.2.1
  hydrated_bloc: ^9.0.0
  intl: ^0.18.0
  json_annotation: ^4.9.0
  just_audio: ^0.9.38
  open_meteo_api:
    path: packages/open_meteo_api
  package_info_plus: ^8.0.0
  path_provider: ^2.0.8
  rounded_tabbar_widget: ^0.0.2
  shimmer: ^3.0.0
  syncfusion_flutter_calendar: ^25.2.3
  syncfusion_flutter_charts: ^25.2.3+1
  tracking_repository:
    path: packages/tracking_repository
  weather_icons: ^3.0.0
  weather_repository:
    path: packages/weather_repository
  
dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.4.8
  firestore_converter_generator: ^1.0.11
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.3.10
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.3.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/splash_transparent.png
    - assets/weather/
    - assets/tracking/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
   - family: RobotoMono
     fonts:
      - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Regular.ttf     
   - family: SFMono
     fonts:
      - asset: assets/fonts/SF Mono/SF-Mono-Light.otf
        weight: 100 
      - asset: assets/fonts/SF Mono/SF-Mono-LightItalic.otf
        weight: 100 
        style: italic 
      - asset: assets/fonts/SF Mono/SF-Mono-Medium.otf 
        weight: 400
      - asset: assets/fonts/SF Mono/SF-Mono-MediumItalic.otf
        weight: 400
        style: italic
      - asset: assets/fonts/SF Mono/SF-Mono-Regular.otf 
        weight: 500
      - asset: assets/fonts/SF Mono/SF-Mono-RegularItalic.otf 
        weight: 500
        style: italic
      - asset: assets/fonts/SF Mono/SF-Mono-Semibold.otf 
        weight: 600
      - asset: assets/fonts/SF Mono/SF-Mono-SemiboldItalic.otf
        weight: 600
        style: italic
      - asset: assets/fonts/SF Mono/SF-Mono-Bold.otf 
        weight: 700
      - asset: assets/fonts/SF Mono/SF-Mono-BoldItalic.otf 
        weight: 700
        style: italic
      - asset: assets/fonts/SF Mono/SF-Mono-Heavy.otf 
        weight: 900
      - asset: assets/fonts/SF Mono/SF-Mono-HeavyItalic.otf 
        weight: 900
        style: italic